/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as VPublicIdRouteImport } from './routes/v.$publicId'
import { Route as VerifyPublicIdRouteImport } from './routes/verify.$publicId'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app/audit'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppLocationsIndexRouteImport } from './routes/_authenticated/app/locations.index'
import { Route as AuthenticatedAppLocationsIdRouteImport } from './routes/_authenticated/app/locations.$id'
import { Route as AuthenticatedAppVerificationsIndexRouteImport } from './routes/_authenticated/app/verifications.index'
import { Route as AuthenticatedAppVerificationsIdRouteImport } from './routes/_authenticated/app/verifications.$id'
import { Route as AuthenticatedAppVerificationsNewRouteImport } from './routes/_authenticated/app/verifications.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const VPublicIdRoute = VPublicIdRouteImport.update({
  id: '/v/$publicId',
  path: '/v/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPublicIdRoute = VerifyPublicIdRouteImport.update({
  id: '/verify/$publicId',
  path: '/verify/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/app/dashboard',
    path: '/app/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLocationsIndexRoute =
  AuthenticatedAppLocationsIndexRouteImport.update({
    id: '/app/locations/',
    path: '/app/locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLocationsIdRoute =
  AuthenticatedAppLocationsIdRouteImport.update({
    id: '/app/locations/$id',
    path: '/app/locations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVerificationsIndexRoute =
  AuthenticatedAppVerificationsIndexRouteImport.update({
    id: '/app/verifications/',
    path: '/app/verifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVerificationsIdRoute =
  AuthenticatedAppVerificationsIdRouteImport.update({
    id: '/app/verifications/$id',
    path: '/app/verifications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVerificationsNewRoute =
  AuthenticatedAppVerificationsNewRouteImport.update({
    id: '/app/verifications/new',
    path: '/app/verifications/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/v/$publicId': typeof VPublicIdRoute
  '/verify/$publicId': typeof VerifyPublicIdRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/locations/$id': typeof AuthenticatedAppLocationsIdRoute
  '/app/verifications/$id': typeof AuthenticatedAppVerificationsIdRoute
  '/app/verifications/new': typeof AuthenticatedAppVerificationsNewRoute
  '/app/locations/': typeof AuthenticatedAppLocationsIndexRoute
  '/app/verifications/': typeof AuthenticatedAppVerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/v/$publicId': typeof VPublicIdRoute
  '/verify/$publicId': typeof VerifyPublicIdRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/locations/$id': typeof AuthenticatedAppLocationsIdRoute
  '/app/verifications/$id': typeof AuthenticatedAppVerificationsIdRoute
  '/app/verifications/new': typeof AuthenticatedAppVerificationsNewRoute
  '/app/locations': typeof AuthenticatedAppLocationsIndexRoute
  '/app/verifications': typeof AuthenticatedAppVerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/v/$publicId': typeof VPublicIdRoute
  '/verify/$publicId': typeof VerifyPublicIdRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/locations/$id': typeof AuthenticatedAppLocationsIdRoute
  '/_authenticated/app/verifications/$id': typeof AuthenticatedAppVerificationsIdRoute
  '/_authenticated/app/verifications/new': typeof AuthenticatedAppVerificationsNewRoute
  '/_authenticated/app/locations/': typeof AuthenticatedAppLocationsIndexRoute
  '/_authenticated/app/verifications/': typeof AuthenticatedAppVerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/how-it-works'
    | '/pricing'
    | '/reset-password'
    | '/trust'
    | '/v/$publicId'
    | '/verify/$publicId'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/locations/$id'
    | '/app/verifications/$id'
    | '/app/verifications/new'
    | '/app/locations/'
    | '/app/verifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/how-it-works'
    | '/pricing'
    | '/reset-password'
    | '/trust'
    | '/v/$publicId'
    | '/verify/$publicId'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/locations/$id'
    | '/app/verifications/$id'
    | '/app/verifications/new'
    | '/app/locations'
    | '/app/verifications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/how-it-works'
    | '/pricing'
    | '/reset-password'
    | '/trust'
    | '/v/$publicId'
    | '/verify/$publicId'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/locations/$id'
    | '/_authenticated/app/verifications/$id'
    | '/_authenticated/app/verifications/new'
    | '/_authenticated/app/locations/'
    | '/_authenticated/app/verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrustRoute: typeof TrustRoute
  VPublicIdRoute: typeof VPublicIdRoute
  VerifyPublicIdRoute: typeof VerifyPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$publicId': {
      id: '/v/$publicId'
      path: '/v/$publicId'
      fullPath: '/v/$publicId'
      preLoaderRoute: typeof VPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$publicId': {
      id: '/verify/$publicId'
      path: '/verify/$publicId'
      fullPath: '/verify/$publicId'
      preLoaderRoute: typeof VerifyPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/locations/': {
      id: '/_authenticated/app/locations/'
      path: '/app/locations'
      fullPath: '/app/locations/'
      preLoaderRoute: typeof AuthenticatedAppLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/locations/$id': {
      id: '/_authenticated/app/locations/$id'
      path: '/app/locations/$id'
      fullPath: '/app/locations/$id'
      preLoaderRoute: typeof AuthenticatedAppLocationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/verifications/': {
      id: '/_authenticated/app/verifications/'
      path: '/app/verifications'
      fullPath: '/app/verifications/'
      preLoaderRoute: typeof AuthenticatedAppVerificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/verifications/$id': {
      id: '/_authenticated/app/verifications/$id'
      path: '/app/verifications/$id'
      fullPath: '/app/verifications/$id'
      preLoaderRoute: typeof AuthenticatedAppVerificationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/verifications/new': {
      id: '/_authenticated/app/verifications/new'
      path: '/app/verifications/new'
      fullPath: '/app/verifications/new'
      preLoaderRoute: typeof AuthenticatedAppVerificationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppLocationsIdRoute: typeof AuthenticatedAppLocationsIdRoute
  AuthenticatedAppVerificationsIdRoute: typeof AuthenticatedAppVerificationsIdRoute
  AuthenticatedAppVerificationsNewRoute: typeof AuthenticatedAppVerificationsNewRoute
  AuthenticatedAppLocationsIndexRoute: typeof AuthenticatedAppLocationsIndexRoute
  AuthenticatedAppVerificationsIndexRoute: typeof AuthenticatedAppVerificationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppLocationsIdRoute: AuthenticatedAppLocationsIdRoute,
  AuthenticatedAppVerificationsIdRoute: AuthenticatedAppVerificationsIdRoute,
  AuthenticatedAppVerificationsNewRoute: AuthenticatedAppVerificationsNewRoute,
  AuthenticatedAppLocationsIndexRoute: AuthenticatedAppLocationsIndexRoute,
  AuthenticatedAppVerificationsIndexRoute:
    AuthenticatedAppVerificationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrustRoute: TrustRoute,
  VPublicIdRoute: VPublicIdRoute,
  VerifyPublicIdRoute: VerifyPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
